### ISSUE TITLE
vaadin-grid theme dom-module ID issue?

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-material-theme#12] opened 2017-10-26 13:33 UTC
Shouldn't this be something like `material-grid` as to not conflict with the Valo theme module of the same ID?

https://github.com/vaadin/vaadin-material-theme/blob/061040fe69b5ae69c66858ae61f1b352518e4264/vaadin-grid.html#L5

**Comment by jouni** [comment] 2017-10-26 13:53
Yes, duplicate of #10. Haven’t gotten around to fixing it yet. PR welcome :)

**Comment by moderndeveloperllc** [comment] 2017-10-26 13:54
Oops! Didn't check as I should have.

**Closed by jouni** 2017-10-26 13:54 UTC

**Comment by jouni** [comment] 2017-10-26 13:56
No worries! You might assume such a simple thing would be fixed right away so there wouldn’t be any duplicates 😄
